from django.urls import path
from . import  views
urlpatterns = [
    path('',views.index,name='index'),
    path('product-detail/<str:code>/', views.product_detail, name='product_detail'),
    path('register/', views.register, name='register'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('category-filter/<int:category_id>/', views.category_filter, name='category_filter'),
    path('products/category/<int:category_id>/', views.category_filter, name='index_by_category'),
    path('products/all/', views.all_products, name='all_products'),
    path('add-to-cart/<str:product_code>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<str:product_code>/', views.remove_from_cart, name='remove_from_cart'),
    path('update-cart-quantity/<str:product_code>/', views.update_cart_quantity, name='update_cart_quantity'),
    path('add-wishlist/<str:product_code>/', views.add_wishlist, name='add_wishlist'),
    path('delete-wishlist/<str:product_code>/', views.delete_wishlist, name='delete_wishlist'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.order_history, name='order_history'),
    path('orders/<str:code>/', views.order_detail, name='order_detail'),
    path('api/live-search/', views.live_search, name='live_search'),
    path('api/category-products/<int:category_id>/', views.category_products_api, name='category_products_api'),
]
