# Generated by Django 5.2.14 on 2026-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, help_text='Telegram kanal yoki guruh havolasi (masalan: https://t.me/sizning_kanal)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(1, 'Faol savat'), (2, 'Qabul qilindi'), (3, "Yo'lda"), (4, 'Yetkazilgan'), (5, 'Qaytarilgan')], default=1),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default="To'garak shop", max_length=150),
        ),
    ]
