# Generated by Django 5.1.2 on 2026-08-14 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_address_id_alter_banner_id_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=uuid.uuid4, max_length=150, unique=True)),
                ('provider', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum Bank'), ('cash', "Yetkazilganda naqd to'lov")], db_index=True, default='cash', max_length=30)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('initiated', 'Boshlandi'), ('paid', "To'landi"), ('failed', 'Xatolik'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Qaytarildi')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, default='card', max_length=50)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.cart')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
