# Generated by Django 5.1.2 on 2026-08-15 07:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='financial_status',
            field=models.CharField(choices=[('unpaid', "To'lanmagan"), ('partially_paid', "Qisman to'langan"), ('fully_paid', "To'liq to'langan"), ('refunded', 'Qaytarilgan')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cart',
            name='prepayment_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('prepayment', "Oldindan to'lov"), ('balance', "Qoldiq to'lov"), ('full', "To'liq to'lov")], db_index=True, default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_cash_balance',
            field=models.BooleanField(default=True, verbose_name="Yetkazilganda naqd qoldiq to'loviga ruxsat"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_online_balance_payment',
            field=models.BooleanField(default=True, verbose_name="Qoldiqni onlayn to'lashga ruxsat"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='prepayment_enabled',
            field=models.BooleanField(default=True, verbose_name="Oldindan to'lov tizimi yoqilgan"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='prepayment_percent',
            field=models.IntegerField(choices=[(0, "0% (Faqat yetkazilganda to'lash)"), (30, "30% (Oldindan to'lov)"), (50, '50% (Yarmi oldindan)'), (100, "100% (To'liq onlayn to'lov)")], default=30, verbose_name="Oldindan to'lov foizi"),
        ),
    ]
