# Generated by Django 5.1.2 on 2026-08-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_cart_financial_status_cart_prepayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allowed_prepayment_percentages',
            field=models.CharField(default='30,50,100', help_text="Vergul bilan ajratilgan foizlar ro'yxati, masalan: 30,50,100 yoki 0,30,50,100", max_length=100, verbose_name="Ruxsat etilgan oldindan to'lov foizlari"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='prepayment_percent',
            field=models.IntegerField(choices=[(0, "0% (Faqat yetkazilganda to'lash)"), (30, "30% (Oldindan to'lov)"), (50, '50% (Yarmi oldindan)'), (100, "100% (To'liq onlayn to'lov)")], default=30, verbose_name="Standart oldindan to'lov foizi"),
        ),
    ]
