# Generated by Django 5.1.2 on 2026-08-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sitesettings_allowed_prepayment_percentages_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
    ]
