# Generated by Django 5.1.5 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_cart_inventory_fields_cartproduct_unit_price_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 0)), name='product_count_non_negative'),
        ),
    ]
